@startuml dietary_restriction_customer
left to right direction
actor Dietary_Restriction_Customer
rectangle "System" as system {
  (Login)
  (Register)
  (View Cart)
  (View Menu)
  (View Ingredients)
  (Customize Order)
  (View Profile)
  (Logout)
}
Dietary_Restriction_Customer --> (Login)
Dietary_Restriction_Customer --> (Register)
Dietary_Restriction_Customer --> (View Cart)
Dietary_Restriction_Customer --> (View Menu)
Dietary_Restriction_Customer --> (View Ingredients)
Dietary_Restriction_Customer --> (Customize Order)
Dietary_Restriction_Customer --> (View Profile)
Dietary_Restriction_Customer --> (Logout)
@enduml