@startuml employee
left to right direction
actor Employee
rectangle "System" as system {
  (Login)
  (View Orders)
  (View Schedule)
  (Hours Settings)
  (View Employee Profile)
  (Logout)
}
Employee --> (Login)
Employee --> (View Orders)
Employee --> (View Schedule)
Employee --> (Hours Settings)
Employee --> (View Employee Profile)
Employee --> (Logout)
@enduml