@startuml login
actor Manager
boundary "System" as system
control "Options" as options
control "Authentication" as auth
Manager -> system: Login
activate system
system -> auth: login_pipeline(username, password)
activate auth
auth --> system: True
deactivate auth
system -> options: view_inventory()
system -> options: view_business_statistics()
system -> options: view_schedule()
system -> options: view_employees()
activate options
options --> system: None
deactivate options
system -> system: redirect to home page
deactivate system
@enduml

@startuml login
actor Employee
boundary "System" as system
control "Clock" as clock
control "Authentication" as auth
Employee -> system: Login
activate system
system -> auth: login_pipeline(username, password)
activate auth
auth --> system: True
deactivate auth
system -> clock: add_clockin(username, time)
activate clock
clock --> system: None
system -> clock: end_clockin(username, time)
clock --> system: None
deactivate clock
system -> system: redirect to home page
deactivate system
@enduml

@startuml login
actor Customer
boundary "System" as system
entity "Sessions" as sessions
control "Authentication" as auth
database "Menu" as menu
collections "Order List" as orderlist
Customer -> system: Login
activate system
system -> auth: login_pipeline(username, password)
activate auth
auth --> system: True
deactivate auth
system -> sessions: add_new_session(username, db)
activate sessions
sessions -> menu: select_items()
sessions -> menu: customize_items()
activate menu
menu --> sessions: Checkout
deactivate menu
sessions -> orderlist: place_order(username, items)
activate orderlist
sessions --> system: None
deactivate orderlist
deactivate sessions
system -> system: redirect to home page
deactivate system
@enduml

@startuml Orders
actor Chef
boundary "System" as system
collections "Order List" as orderlists
control "Authentication" as auth
Chef -> system: Login
activate system
system -> auth: login_pipeline(username, password)
activate auth
auth --> system: True
deactivate auth
system -> orderlists: view_new_orders()
activate orderlists
orderlists --> system: None
deactivate orderlists
system -> system: redirect to home page
deactivate system
@enduml


